<?php

/**
 * @category    Temando
 * @package     Temando_Temando
 */

/** @var \Temando\Temando\Block\ListStore\MapBox $block */
?>
<div class="map-box-container col-sm-8 col-xs-12 pull-right" >
    <div class="googlemap"></div>
</div>
<div class="location-box-view" style="display: none;">
    <div class="widget-mylocation">
        <button id="widget-mylocation-button" class="widget-mylocation-button" title="Show My Location">
            <div class="widget-mylocation-cookieless"></div>
        </button>
    </div>
</div>